apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chart05-appset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/mteodor/helm-charts
        revision: HEAD
        directories:
          - path: charts/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "xxxxx"
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: cluster11
        namespace: '{{.path.basename}}'-05
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
